---
- set_fact: build_home="/usr/src/jenkinsbuild/workspace/shamash"
- set_fact: build_log_directory="/usr/src/log"
- set_fact: logfile="{{build_log_directory}}/shamash.log"

- name: Make log directory structure
  file: path={{build_log_directory}} state=directory mode=0755 group=users

- name: Make shamash target directory structure
  file: path={{shamash_root}}/ state=directory mode=0755 group=users

- name: Copy the shamash sources to staging directory
  command: rsync -ar --delete {{ build_home }}/ {{shamash_root}}/source

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{shamash_root}}/Dockerfile mode=0755

- name: Build the shamash docker image (this takes about 2 minutes)
  shell: docker build --tag={{ shamash_docker_image|quote }} --force-rm=true {{shamash_root}} > {{logfile}} 2>&1
  register: image

- name: Push shamash docker image if built
  when: image.changed
  shell: docker push {{ shamash_docker_image|quote }}
